// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBA3I3xdZOxa8lymtv-k5RRrr8jB_aD22o',
    appId: '1:238735831976:web:d8355b5ad1481c2d59e39d',
    messagingSenderId: '238735831976',
    projectId: 'insta-clone-417eb',
    authDomain: 'insta-clone-417eb.firebaseapp.com',
    storageBucket: 'insta-clone-417eb.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCy2y8ynRBefE0u-OKia_L83xYMTIWjre0',
    appId: '1:238735831976:android:6d09aecb06e170a659e39d',
    messagingSenderId: '238735831976',
    projectId: 'insta-clone-417eb',
    storageBucket: 'insta-clone-417eb.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFUkNdf1kQ1jNcdoUEWQqcJ1PldWfuq-M',
    appId: '1:238735831976:ios:43b9cd21dacc9b8b59e39d',
    messagingSenderId: '238735831976',
    projectId: 'insta-clone-417eb',
    storageBucket: 'insta-clone-417eb.appspot.com',
    iosBundleId: 'com.example.instagramFlutter',
  );
}
